Upload artifacts to s3
atlassian/workspace pull request #2
Opened 2019-02-22 13:55 UTC by wyrzyk

2019-02-22 13:59 UTC, dagguh approved these changes

2019-02-22 13:59 UTC, dagguh commented on scripts/upload-artifacts.sh
> +export ARTIFACTS_BUCKET="jpt-travis-ci-pipeline"
"JPT Travis CI pipeline" has a teeny-tiny scent of Bitbucket Pipelines
```suggestion
export ARTIFACTS_BUCKET="jpt-travis-ci-artifacts"
```
Just a nit 😉

2019-02-22 14:01 UTC, dagguh requested changes
It failed with:
```
./scripts/upload-artifacts.sh: line 5: artifacts: command not found
```

2019-04-15 07:13 UTC, closed without merging

2019-04-15 08:25 UTC, wyrzyk commented
AFAIK we can get artifacts upload out of the box in Circle CI.

2019-04-15 08:55 UTC, dagguh commented
Correct. E.g.: https://circleci.com/gh/atlassian/aws-infrastructure/19#artifacts/containers/0